---
title: "index.qmd"
output: 
  html: default
  markdown: default
---

## \## Intro





```{r}
mpg %>% dplyr::glimpse()
```

```{r}
mpg %>% mosaic::inspect()
```

```{r}
mpg %>% skimr::skim()
```

```{r}
mpg_modified <- mpg %>%
  dplyr::mutate(
    cyl = as_factor(cyl),
    fl = as_factor(fl),
    drv = as_factor(drv),
    class = as_factor(class),
    trans = as_factor(trans)
  )
glimpse(mpg_modified)
```

```{r}

#| label: setup 
library(tidyverse)
library(ggformula)
library(babynames)
```

```{r}
babynames %>% dplyr::glimpse()
```

```{r}
babynames %>% mosaic::inspect()
```

```{r}
babynames %>% skimr::skim()
```

```{r}
babynames_modified <- babynames %>%
  dplyr::mutate(
    year = as.integer(year),
    sex = as_factor(sex)
  )
glimpse(babynames_modified)
```

```{r}
 mpg_modified %>%
  group_by(cyl) %>%
  summarize(average_hwy = mean(hwy), count = n())
```

```{r}
 mpg_modified %>%
  group_by(manufacturer) %>%
  summarize(average_cty = mean(cty), count = n())
```

## Analyzing math anxiety data

```{r}
math_anxiety <- read_csv("../../data/MathAnxiety.csv")
math_anxiety 
```

```{r}
math_anxiety %>% dplyr::glimpse()
```

```{r}
star <- read_csv("../../data/star_trek_books.csv")
star
```

```{r}
math_anxiety <- read_delim(file = "../../data/MathAnxiety.csv", delim = ";")
math_anxiety

```

```{r}
math_anxiety %>% dplyr::glimpse()
```

```{r}
math_anxiety %>% mosaic::inspect()
```

```{r}
math_anxiety %>% skimr::skim()
```

```{r}

math_anxiety_modified <- math_anxiety %>%
  dplyr::mutate(
    Grade = as_factor(Grade),
    Gender= as_factor(Gender)
    
  )
glimpse(math_anxiety_modified)
```

```{r}
math_anxiety_modified <- math_anxiety %>% 
  dplyr::mutate(
   
    Age= as.integer(Age/120),
    Grade = as_factor(Grade),
    Gender= as_factor(Gender)
    
  )
glimpse(math_anxiety_modified)
```

```{r}
 math_anxiety_modified %>%
  group_by(Gender) %>%
  summarize(average_anxiety = mean(RCMAS), count = n())
```

```{r}
math_anxiety_modified %>%
  group_by(Gender) %>%
  summarize(average_anxietyamas = mean(AMAS), average_anxietyrcmas = mean(RCMAS), count = n())
```

```{r}
math_anxiety_modified %>%
  group_by(Grade,Gender) %>%
  summarize(average_anxiety = mean(AMAS), count = n())
```
